---
label: default
hide_body: false
fields:
- type: text
  label: Title
  name: title
  config:
    required: true
- type: datetime
  label: Date
  name: date
  config:
    date_format: YYYY/MM/DD
- type: text
  name: description
  label: Description
- type: file
  name: image
  label: Image
- type: tag_list
  label: Tags
  name: tags
